### ISSUE TITLE
Relatively large amount of data downloaded?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/trix-js#1]
I made a script to try out the query in the README, and I found that it was resulting in a 10.25MB download (running sudo nethogs -v3 in one window, node index.js for the readme example in another)

Is this expected or is there any way to optimize the amount of data downloaded?

**Comment by rbuels** [comment]
@mattmorgan6 what do you think about this?

**Comment by mattmorgan6** [comment]
@cmdcolin This is happening because the chunk contains the word "of" which has 9.9 MB of results which makes for a large chunk. To verify that this is a somewhat rare case, I just ran a calculation and the average chunk size is 223 Kilobytes, so generally it will not download so much data.

**Comment by mattmorgan6** [comment]
@rbuels I am thinking we should change the example search string. I'm also going to look and see if I can optimize this.

**Comment by cmdcolin** [comment]
Good to know, I imagine if there is a way to optimize it would be great!

**Comment by mattmorgan6** [comment]
Resolved by #2
